# Cloudflare Pages configuration
name = "mindlang-dev"
compatibility_date = "2026-02-05"
pages_build_output_dir = "out"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.preview]
vars = { ENVIRONMENT = "preview" }
